---
driver:
  name: docker
  use_sudo: false

provisioner:
  hosts: test-kitchen
  name: ansible_playbook
  ansible_verbosity: 2
  ansible_verbose: true
  #requirements_path: requirements-test.txt

platforms:
  - name: debian-wheezy
    driver_config:
      image: debian:wheezy-backports
      platform: debian

suites:
  - name: default
