---
# tasks file for ansible-supervisord

#################################################################
# Copy the supervisor.conf.j2 template in /etc/supervisor/conf.d
# for each supervisord_programs configured.
#################################################################

- name: Get init-system-helper
  get_url: 
   url: http://archive.ubuntu.com/ubuntu/pool/main/i/init-system-helpers/init-system-helpers_1.57_all.deb
   dest: /tmp/init-system-helpers_1.57_all.deb

- name: Get Supervisor 4 (python3)
  get_url: 
   url: http://archive.ubuntu.com/ubuntu/pool/universe/s/supervisor/supervisor_4.1.0-1ubuntu1_all.deb
   dest: /tmp/supervisor_4.1.0-1ubuntu1_all.deb

- name: Install init-system-helper version 1.57
  apt: 
    deb: /tmp/init-system-helpers_1.57_all.deb

- name: Install supervisor
  apt:
    deb: /tmp/supervisor_4.1.0-1ubuntu1_all.deb

- name: Install superlance
  pip:
    name: superlance
    state: present

- name: Setup main supervisor config
  template: src=main-supervisor.conf.j2 dest=/etc/supervisor/supervisord.conf
  tags: supervisord-main-config
  notify:
    - restart supervisord

- name: Setup supervisor programs
  template: src=supervisor.conf.j2 dest={{ supervisord_config_location }}/{{ item.value['program_name'] }}.conf
  with_dict: "{{ supervisord_programs }}"
  notify:
    - reread supervisord
    - update supervisord

- name: Setup supervisor events
  template: src=supervisor-events.conf.j2 dest={{ supervisord_config_location }}/{{ item.value['event_name'] }}.conf
  with_dict: "{{ supervisord_events }}"
  notify:
    - reread supervisord
    - update supervisord
