---
# tasks file for ansible-supervisord

#################################################################
# Copy the supervisor.conf.j2 template in /etc/supervisor/conf.d
# for each supervisord_programs configured.
#################################################################

- name: Supervisord | Ubuntu / Debian | Install
  apt:
    name: '{{ item }}'
    cache_valid_time: 3600
    update_cache: yes
    state: latest
  with_items:
    - 'supervisor'
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'

- name: Setup main supervisor config
  template: src=main-supervisor.conf.j2 dest=/etc/supervisor/supervisord.conf
  tags: supervisord-main-config
  notify:
    - restart supervisord

- name: Setup supervisor config
  template: src=supervisor.conf.j2 dest={{ supervisord_config_location }}/{{ item.value['program_name'] }}.conf
  with_dict: supervisord_programs
  notify:
    - reread supervisord
    - update supervisord
