---
# tasks file for ansible-supervisord

#################################################################
# Copy the supervisor.conf.j2 template in /etc/supervisor/conf.d
# for each supervisord_programs configured.
#################################################################


# Setup supervisor from backports if debian version < jessie
- name: Supervisord | Debian < 8 | Install
  apt:
    name: '{{ item }}'
    cache_valid_time: 3600
    update_cache: yes
    state: latest
    default_release: wheezy-backports
  with_items:
    - supervisor
  when: ansible_distribution == 'Debian' and ansible_lsb.major_release|int < 8

- name: Supervisord | Ubuntu / Debian >= 8 | Install
  pip:
    name: supervisor
  when: ansible_distribution == 'Ubuntu' or (ansible_distribution == 'Debian' and ansible_lsb.major_release|int >= 8)

- name: Install superlance
  pip:
    name: superlance
    state: present

- name: Setup supervisor dir
  file:
    path: /etc/supervisor/conf.d
    state: directory

- name: Setup main supervisor config
  template: src=main-supervisor.conf.j2 dest=/etc/supervisor/supervisord.conf
  tags: supervisord-main-config
  notify:
    - restart supervisord

- name: Setup supervisor programs
  template: src=supervisor.conf.j2 dest={{ supervisord_config_location }}/{{ item.value['program_name'] }}.conf
  with_dict: "{{ supervisord_programs }}"
  notify:
    - reread supervisord
    - update supervisord

- name: Setup supervisor events
  template: src=supervisor-events.conf.j2 dest={{ supervisord_config_location }}/{{ item.value['event_name'] }}.conf
  with_dict: "{{ supervisord_events }}"
  notify:
    - reread supervisord
    - update supervisord
