---
# handlers file for ansible-supervisord

- name: reread supervisord
  command: supervisorctl reread

- name: update supervisord
  command: supervisorctl update

- name: restart supervisord
  shell: /etc/init.d/supervisor stop && sleep 10 && /etc/init.d/supervisor start
